name: Pre-release
on:
  push:
    branches:
      - beta # branch you want to trigger pre-releases from
  workflow_dispatch: # or manually trigger
    inputs:
      preid:
        description: 'Pre-release identifier (e.g., beta, alpha)'
        required: true
        default: 'beta'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn prettier --check .
      - run: yarn tsc

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn install --immutable
      - run: yarn test

  prerelease:
    name: Create Pre-release
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Enter Pre-release Mode
        run: |
          TIMESTAMP=$(date +%s)
          echo "Entering pre-release mode with tag: ${{ github.event.inputs.preid || 'beta' }}-${TIMESTAMP}"
          yarn changeset pre enter "${{ github.event.inputs.preid || 'beta' }}-${TIMESTAMP}"

      - name: Increment Pre-release Version
        run: |
          echo "Pre-release version increment"
          yarn changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Exit Pre-release Mode
        run: yarn changeset pre exit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Pre-release
        run: |
          echo "Publishing pre-release with tag: ${{ github.event.inputs.preid || 'beta' }}-${TIMESTAMP}"
          echo "Typescript version: $(tsc --version)"          
          yarn ts
          yarn changeset publish --tag "${{ github.event.inputs.preid || 'beta' }}-${TIMESTAMP}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Cleanup Temporary Files
        if: always()
        run: |
          echo "Cleaning up temporary files"
          rm -f ~/.npmrc
