name: Pre-release
on:
  push:
    branches:
      - beta # or any branch you want to trigger pre-releases from
  workflow_dispatch: # or manually trigger
    inputs:
      preid:
        description: 'Pre-release identifier (e.g., beta, alpha)'
        required: true
        default: 'beta'

jobs:
  prerelease:
    name: Create Pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
      - name: Install Dependencies
        run: yarn install --immutable

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Pre-release
        run: |
          echo "Create pre-release with tag: ${{ github.event.inputs.preid || 'beta' }}"
          yarn changeset pre enter ${{ github.event.inputs.preid || 'beta' }}
          yarn changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Exit Pre-release Mode
        run: yarn changeset pre exit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Pre-release
        run: |
          echo "Publishing pre-release with tag: ${{ github.event.inputs.preid || 'beta' }}"
          echo "Typescript version: $(tsc --version)"          
          yarn ts
          yarn changeset publish --tag ${{ github.event.inputs.preid || 'beta' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
