name: Pre-release
on:
  push:
    branches:
      - beta # or any branch you want to trigger pre-releases from
  workflow_dispatch: # or manually trigger
    inputs:
      preid:
        description: 'Pre-release identifier (e.g., beta, alpha)'
        required: true
        default: 'beta'

jobs:
  prerelease:
    name: Create Pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
      - name: Install Dependencies
        run: yarn install --immutable

      - name: Create Pre-release
        id: changesets
        uses: changesets/action@v1
        with:
          publish: ./scripts/prerelease-release.sh
          version: ./scripts/prerelease-version.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
